### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by hannahtobiason** [josephos416/BreakBread#3]
Create each separate web page involved in how the user navigates, leaving the functional pages empty for now and focusing on the sign up, log in, friends, and profile page. This is not creating the functionality, strictly the ability to link the pages to each other and set up the overall skeleton of the website.

Time Estimate: 10 Hrs
Actual Time:
Erik: 5 Hrs

**Comment by Eriken79** [comment]
Create each separate web page involved in how the user navigates, leaving the functional pages empty for now and focusing on the sign up, log in, friends, and profile page. This is not creating the functionality, strictly the ability to link the pages to each other and set up the overall skeleton of the website.
